@host=http://localhost:5159
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJmNDhjODI0YS04NzY0LTQ0YTAtOTAyZC1mZDY0MWY2NDQxOWMiLCJnaXZlbl9uYW1lIjoibW9oYW1lZCIsImZhbWlseV9uYW1lIjoiYWxxYWRlZXJ5IiwianRpIjoiNDEwMjQ3MjQtNzE2NS00YzJmLTk0YTEtYjA0ZjBkZGQ5YjYxIiwiZXhwIjoxNjg2NzU3MjQzLCJpc3MiOiIgRGlubmVyIiwiYXVkIjoiRGlubmVyIn0.G9J-f8KatTED7Kp7O-WVrLhDkbS2sEdP10Yrtw0gvsM
@hostId=123

POST  {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "First Good Menu",
    "description": "A menu with yummy food",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "Deep fried pickles"
                }
            ]
        }
    ]
}
